# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
	{ on = "<C-t>", run = 'shell "$SHELL" --block', desc = "Open shell here" },
	{ on = "<C-n>", run = 'shell --orphan foot', desc = "Open new terminal window" },
  { on = "p", run = "plugin ucp paste notify", desc = "Paste" },
  { on = "y", run = "plugin ucp copy notify", desc = "Copy" }
]


